---
# tasks file for web
- name: Install Zabbix Web
  yum:
    name: zabbix-web-mysql
    state: present

- name: Config Zabbix Web
  copy:
    src: zabbix.conf
    dest: /etc/httpd/conf.d/zabbix.conf
  notify: Restart HTTPD

- name: Start HTTPD and Firewalld
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - httpd
    - firewalld

- name: Config Firewalld for HTTP Service
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Config Firewalld for HTTPS Service
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled
