---
- name: Adding Zabbix Repo To All Machines
  hosts: controllermachine, servermachine, clientmachine
  roles:
    - repo

- name: Running Zabbix Server On Server Machine
  hosts: servermachine
  roles:
    - db
    - server
    - web


- name: Running Zabbix Agent On Client Machine
  hosts: clientmachine
  roles:
    - agent
